### ISSUE TITLE
User can add Workout 

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/lifted#1]
Functionality : 
User can add Workout. 

## ✅ Task List
- [x] create main page with navbar and graphs. 
- [x] create "workout overview" page 
- [x] create "workout" page for actual addition of workout.
- [x] weight and routine is optional, everything else are required.
