### ISSUE TITLE
user can view the workout graph

### ISSUE THREAD

**Issue by Adam-SungMin-Park** [Adam-SungMin-Park/lifted#4]
## ✅ Task List
- [x] fetch the data from the database. 
- [x] clear connection between express and fetch . 
- [x] make sure to send necessary response from app.get
- [x] setState using the received data. 
- [x] install/ prepare chart.js
- [x] lmport/ export the necessary files for the graph. 
- [x] pass the props to the graph file
- [x] update the graph with the given data.
